<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="Model/Skin/css/style.css">
    <title>product</title>
  </head>
  <body>
    <?php require_once "View/html/header.phtml" ?>
    <table>
    	<tr>
    	<td><h3>Add Product<h3></td>
    	<td><a class="btn btn-primary mx-2" href="<?php echo $this->getModelUrl()->getUrl('grid',null,null); ?>">cancel</a> </td>
    	<form action="<?php echo $this->getModelUrl()->getUrl('insert'); ?>" method="POST">
    	<td><button class="btn btn-primary"> Add</button></td>
    </tr>
    </table>
<br>
	<table class="table table-bordered">

        <tr>
          <th> SKU</th>
          <td><input type="text" name="product[sku]"></td>
        </tr>
        <tr>
          <th> COST</th>
          <td><input type="number" name="product[cost]"></td>
        </tr>
        <tr>
          <th> PRICE</th>
          <td><input type="number" name="product[price]"></td>
        </tr>
        <tr>
          <th> QUANTITY</th>
          <td><input type="number" name="product[quantity]"></td>
        </tr>
        <tr>
          <th> DESCRIPTION</th>
          <td><input type="text" name="product[description]"></td>
        </tr>
        <tr>
          <th> STATUS</th>
          <td> <select name="product[status]"   >
            <option value="available"name="available">available</option>
            <option value="unavailable"name="unavailable">unavailable</option>
            
          </select> </td>
        </tr>
        <tr>
          <th> COLOR</th>
          <td><select name="product[color]"   >
            <option value="1"name="red">red</option>
            <option value="2"name="green">green</option>
            <option value="3"name="blue">blue</option>
          </select></td>
        </tr>
        <tr>
          <th> MATERIAL</th>
          <td><input type="text" name="product[material]"></td>
        </tr>
        <td>
        </form>
      </table>
      <?php require_once "View/html/footer.phtml" ?>
    </body>
  </html>