<?php
$request = $this->getRequest();
$results = $this->getProductMedia();
?>
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="Model/Skin/css/style.css">
    <title></title>
  </head>
  <body>
    <?php require_once "View/html/header.phtml" ?>


  	 <table>
        <tr>
        <td><h3>product media<h3></td>
        <td><a class="btn btn-primary mx-2" href="<?php echo $this->getModelUrl()->getUrl('grid','product'); ?>">cancel</a> </td>
        <td><a class="btn btn-primary mx-2" href="<?php echo $this->getModelUrl()->getUrl('add','product_media', ['product_id' => $request->getParam('product_id')]); ?>">Add image</a> </td>
      </tr>
      </table>

      <br>

    <table class="table table-bordered">
      <tr>
        <th> IMAGE</th>
        <th> NAME</th>
        <th> THUMBNAIL</th>
        <th> MIDIUM</th>
        <th> LARGE</th>
        <th> SMALL</th>
        <th> GALLARY</th>
        <th> CREATED_AT </th>
        <th> DELETE</th>
      </tr>
      
      <form action="<?php echo $this->getModelUrl()->getUrl('update'); ?>&c=product_media&product_id=<?php echo $request->getParam('product_id'); ?>" method="POST">
        <input class="btn btn-primary mx-5 float-end"  type="submit" name="button" value="delete">

        <input class="btn btn-primary float-end mx-5"  type="submit" name="button" value="update">

        <br>
        <br>
        <br>
        <?php foreach ($results as $result): ?>
        <tr>
          <td class="w-50"><img class="demoimg w-50 h-50" src="View/product_media/image/<?php echo $result['img'] ?>"></td>
          <td><?php echo $result['filename'] ?></td>
          <td><input type="radio" value="<?php echo $result['media_id'] ?>" name="thumbnail" <?php if ($result['thumbnail']){echo "checked";}?>></td>
          <td><input type="radio" value="<?php echo $result['media_id'] ?>" name="midium"<?php if ($result['midium']){echo "checked";}?>></td>
          <td><input type="radio" value="<?php echo $result['media_id'] ?>" name="large" <?php if ($result['large']){echo "checked";}?>></td>
          <td><input type="radio" value="<?php echo $result['media_id'] ?>" name="small" <?php if ($result['small']){echo "checked";}?>></td>
          <td><input type="checkbox" value="<?php echo $result['media_id'] ?>" name="gallary[]" <?php if ($result['gallary']){echo "checked";}?>></td>
          <td><?php echo $result['created_at'] ?></td>
          <td><input type="checkbox" value="<?php echo $result['media_id'] ?>" name="delete_image[]" ></td>
        </tr>
        <?php endforeach; ?>
      </table>
    </form>
  </body>
</html>