<?php
$shipping_methods = $this->getShippingMethod();
?>
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="Model/Skin/css/style.css">
    <title>shipping method</title>
  </head>
  <body>
    <?php require_once "View/html/header.phtml" ?>

     <div><div><h3>SHIPPING METHOD</h3></div><div style="margin-left:640px;margin-top: 15px;"><a  class="btn btn-primary" href="<?php echo $this->getModelUrl()->getUrl('add'); ?>">
    add shipping method
  </a></div></div>

<br>

<table class="table table-bordered">
  <tr>
    <th> SHIPPING_METHOD_ID</th>
    <th> NAME</th>
    <th> AMOUNT</th>
    <th> STATUS</th>
    <th> </th>
    <th> </th>
  </tr>
  <tr>
    <?php foreach ($shipping_methods as $shipping_method): ?>
    <td><?php echo $shipping_method['shiping_method_id'] ?></td>
    <td> <?php echo $shipping_method['name'] ?> </td>
    <td> <?php echo $shipping_method['amount'] ?> </td>
    <td> <?php echo $shipping_method['status'] ?> </td>
    <td><a href="<?php echo $this->getModelUrl()->getUrl('edit','shippingMethod',['shiping_method_id' => $shipping_method['shiping_method_id']]); ?>">edit</a></td>
    <td><a href="<?php echo $this->getModelUrl()->getUrl('delete','shippingMethod',['shiping_method_id' => $shipping_method['shiping_method_id']]); ?>">delete<a></td>
  </tr>
  <?php endforeach; ?>
</table>
</body>
<?php require_once "View/html/footer.phtml" ?>
</html>