<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="Model/Skin/css/style.css">
        <title>payment method</title>
    </head>
    <body>
        <?php require_once "View/html/header.phtml" ?>
        <table>
            <tr>
                <td><h3>Add payment method<h3></td>
                <td><a class="btn btn-primary mx-2" href="<?php echo $this->getModelUrl()->getUrl('grid',null,null,true); ?>">cancel</a> </td>
                <form action="<?php echo $this->getModelUrl()->getUrl('insert'); ?>" method="POST">
                <td><button class="btn btn-primary"> Add</button></td>
            </tr>
            </table>
            <br>
            
            <table class="table table-bordered">
                <tr>
                    <th>NAME</th>
                    <td><input type="text" name="payment_method[name]"></td>
                </tr>
                <tr>
                    <th>STATUS</th>
                    <td>
                        <select name="payment_method[status]"  >
                            <option value="available"name="available">available</option>
                            <option value="unavailable"name="unavailable">unavailable</option>
                        </select>
                    </td>
                </tr>
            </form>
        </table>
        <?php require_once "View/html/footer.phtml" ?>
    </body>
</html>