<?php
$payment_methods = $this->getPaymentMethod();
?>
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="Model/Skin/css/style.css">
    <title>payment method</title>
  </head>
  <body>
    <?php require_once "View/html/header.phtml" ?>

      <div><div><h3>PAYMENT METHOD</h3></div><div style="margin-left:640px;margin-top: 15px;"><a  class="btn btn-primary" href="<?php echo $this->getModelUrl()->getUrl('add'); ?>">
    add payment method
  </a></div></div>
  <br>

  <table class="table table-bordered">
    <tr>
      <th> PAYMENT_METHOD_ID</th>
      <th> NAME</th>
      <th> STATUS</th>
      <th> </th>
      <th> </th>
    </tr>
    <?php
    foreach ($payment_methods as $payment_method): ?>
    <tr>
      <td><?php echo $payment_method['payment_method_id'] ?></td>
      <td> <?php echo $payment_method['name'] ?></td>
      <td> <?php echo $payment_method['status'] ?></td>
      <td><a href="<?php echo $this->getModelUrl()->getUrl('edit', null, ['payment_method_id' => $payment_method['payment_method_id']]); ?>">edit</a></td>
      <td><a href="<?php echo $this->getModelUrl()->getUrl('delete', null, ['payment_method_id' => $payment_method['payment_method_id']]); ?>?a=delete&c=paymentmethod&payment_method_id=<?php echo $payment_method['payment_method_id'] ?>">delete<a></td>
    </tr>
    <?php endforeach; ?>
  </table>
</body>
<?php require_once "View/html/footer.phtml" ?>
</html>