	<table class="table table-bordered">
	
	<tr hidden>
		<th> ADDRESS_ID</th>
		<td><input type="number" name="customer_address[customer_id]"></td>
	</tr>
	<tr>
		<th> ADDRESS</th>
		<td><input type="text" name="customer_address[address]"></td>
	</tr>
	<tr>
		<th> CITY</th>
		<td><input type="text" name="customer_address[city]"></td>
	</tr>
	<tr>
		<th> STATE</th>
		<td><input type="text" name="customer_address[state]"></td>
	</tr>
	<tr>
		<th> COUNTRY</th>
		<td><input type="text" name="customer_address[country]"></td>
	</tr>
	<tr>
		<th> ZIP_CODE</th>
		<td><input type="number" name="customer_address[zip_code]"></td>
	</tr>
	<td>
		
	</table>