<?php
$customers = $this->getcustomer();
?>
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="Model/Skin/css/style.css">
        <title>customer</title>
    </head>
    <body>

        <?php require_once "View/html/header.phtml" ?>

    	 <div><div><h3>CUSTOMER</h3></div><div style="margin-left:640px;margin-top: 15px;"><a  class="btn btn-primary" href="<?php echo $this->getModelUrl()->getUrl('add'); ?>">
		Add customer
	</a></div></div>
       <br>

	<table class="table table-bordered">

        <tr>
            <th>CUSTOMER_ID</th>
            <th>FIRST_NAME</th>
            <th>LAST_NAME</th>
            <th>EMAIL</th>
            <th>GENDER</th>
            <th>MOBILE</th>
            <th>STATUS</th>
            <th> </th>
            <th> </th>
            <th> </th>
        </tr>
        <?php foreach ($customers as  $customer):?>
        
        <tr>
            <td><?php echo $customer['customer_id'] ?> </td>
            <td><?php echo $customer['first_name'] ?></td>
            <td><?php echo $customer['last_name'] ?></td>
            <td><?php echo $customer['email'] ?></td>
            <td><?php echo $customer['gender'] ?></td>
            <td><?php echo $customer['mobile'] ?></td>
            <td><?php echo $customer['status'] ?></td>
            <td><a href="<?php echo $this->getModelUrl()->getUrl('edit','customer',['customer_id'=>$customer['customer_id']]); ?>">edit</a></td>
            <td><a href="<?php echo $this->getModelUrl()->getUrl('delete','customer',['customer_id'=>$customer['customer_id']]);?>">delete<a></td>
            <td><a href="<?php echo $this->getModelUrl()->getUrl('grid','customer_address',['customer_id'=>$customer['customer_id']]);?>">view address<a></td>
        </tr>
        <?php endforeach; ?>
        
        
        
        
    </table>
</body>
<?php require_once "View/html/footer.phtml" ?>
</html>