<?php
$categories =$this->getCategory();
?>
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="Model/Skin/css/style.css">
    <title>category</title>
  </head>
  
  <body>
    
    <?php require_once "View/html/header.phtml" ?>
	<table>
    	<tr>
    	<td><h3>Add category<h3></td>
    	<td><a class="btn btn-primary mx-2" href="<?php echo $this->getModelUrl()->getUrl('grid',null,null,true); ?>">cancel</a> </td>
    	<form action="<?php echo $this->getModelUrl()->getUrl('insert');?>" method="POST">
    	<td><button class="btn btn-primary"> Add</button></td>
    </tr>
    </table>

        <table class="table table-bordered">

	        <tr>
          <tr> <th> PARENT CATEGORY</th>
          <td><select name="category[parent_id]"class="custom-select" >
            <option value="null" >select</option>
            <?php foreach ($categories as $category): ?>
            <option value="<?php echo $category['category_id'];?>">
              <?php if ($category['parent_id'] != null) {
              foreach ($categories as $main) {
              if ($category['parent_id'] == $main['category_id']) {
              echo $main['name'];
              }
              }
              echo "=>";
            } echo $category['name'];?> 
            
          </option>
            <?php endforeach; ?>
          </select> </td></tr>
          <th> NAME</th>
          <td><input type="text" name="category[name]"></td>
        </tr>
        <tr>
          <th> STATUS</th>
          <td> <select name="category[status]">
            <option value="available"name="available">available</option>
            <option value="unavailable"name="unavailable">unavailable</option>
          </select> </td>
        </tr>
        <tr>
          <th> DESCRIPTION</th>
          <td><input type="text" name="category[description]"></td>
        </tr>
      </form>
    </table>
    <?php require_once "View/html/footer.phtml" ?>
  </body>
</html>