<?php
$categories  = $this->getCategory();
?>
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="Model/Skin/css/style.css">
    <title>product</title>
  </head>
  <body>
    <?php require_once "View/html/header.phtml" ?>
    
    <div><h3>CATEGORY</h3></div><div style="margin-left:640px;margin-top: 15px;"><a  class="btn btn-primary" href="<?php echo $this->getModelUrl()->getUrl('add');?>">
    add category
  </a></button></div></div>
  <br>
  <table class="table table-bordered">
    <tr >
      
      <th> CATEGORY_ID</th>
      <th> NAME</th>
      <th> STATUS</th>
      <th>DESCRIPTION</th>
      <th> </th>
      <th> </th>
    </tr>
    <?php foreach ($categories as $category): ?>
    <tr>
      <td><?php echo $category['category_id'] ?></td>
      <td><?php
        if($category['parent_id'] != null){
        $path = array("");
        $id=$category['parent_id'];
        while ($id != null) {
        foreach ($categories as $main) {
        if($id == $main['category_id'])
        {
        array_push($path, $main['name']);
        $id = $main['parent_id'];
        }
        }
        }
        $path=array_reverse($path);
        $path=implode("=>",$path);
        echo $path;
        }
      echo  $category['name']; ?></td>
      <td><?php echo $category['status'] ?></td>
      <td><?php echo $category['description'] ?></td>
      <td><a href="<?php echo $this->getModelUrl()->getUrl('edit','category',['category_id'=>$category['category_id']]); ?>">edit</a></td>
      <td><a href="<?php echo $this->getModelUrl()->getUrl('delete','category',['category_id'=>$category['category_id']]); ?>">delete<a></td>
    </tr>
    <?php endforeach; ?>
  </table>
</body>
<?php require_once "View/html/footer.phtml" ?>
</html>