<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="Model/Skin/css/style.css">
    <title>salesman</title>
  </head>
  <body>
    <?php require_once "View/html/header.phtml" ?>

   <table>
    <tr>
      <td><h3>Add salesman<h3></td>
      <td><a class="btn btn-primary mx-2" href="<?php echo $this->getModelUrl()->getUrl('grid',null,null,true); ?>">cancel</a> </td>
      <form action="<?php echo $this->getModelUrl()->getUrl('insert'); ?>&c=salesman" method="POST">
        <td><button class="btn btn-primary"> Add</button></td>
      </tr>
    </table>
    <br>

    <table class="table table-bordered">
      <tr>
        <th> FIRST_NAME</th>
        <td><input type="text" name="salesman[first_name]"></td>
      </tr>
      <tr>
        <th> LAST_NAME</th>
        <td><input type="text" name="salesman[last_name]"></td>
      </tr>
      <tr>
        <th> EMAIL</th>
        <td><input type="email" name="salesman[email]"></td>
      </tr>
      <tr>
        <th> GENDER</th>
        <td> <select name="salesman[gender]"   >
          <option value="male"name="male">male</option>
          <option value="female"name="female">female</option>
          
        </select> </td>
      </tr>
      <tr>
        <th> MOBILE</th>
        <td><input type="mobile" name="salesman[mobile]"></td>
      </tr>
      <tr>
        <th> STATUS</th>
        <td>
          <select name="salesman[status]" >
            <option value="available"name="available">available</option>
            <option value="unavailable"name="unavailable">unavailable</option>
          </select>
        </td>
      </tr>
      <tr>
        <th> COMPANY</th>
        <td><input type="text" name="salesman[company]"></td>
      </tr>
      <tr>
        <td>add address</td>
      </tr>
      <?php require 'View/salesman_address/add.phtml' ?>
    </form>
  </table>
</body>
</html>