<?php
$salesmen = $this->getSalesmen();
?>
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="Model/Skin/css/style.css">
    <title>salesman</title>
  </head>
  <body>
    <?php require_once "View/html/header.phtml" ?>

     <div><div><h3>SALESMAN</h3></div><div style="margin-left:640px;margin-top: 15px;"><a  class="btn btn-primary" href="<?php echo $this->getModelUrl()->getUrl('add'); ?>">
    add salesman
  </a></div></div>

  <br>

  <table class="table table-bordered">
    <tr>
      <th> SALESMAN_ID</th>
      <th> FIRST_NAME</th>
      <th> LAST_NAME</th>
      <th> EMAIL</th>
      <th> GENDER</th>
      <th> MOBILE</th>
      <th> STATUS</th>
      <th> COMPANY</th>
      <th> </th>
      <th> </th>
      <th> </th>
      <th> </th>
    </tr>
    <?php
    foreach ($salesmen as $salesman): ?>
    <tr>
      <td><?php echo $salesman['salesman_id'] ?></td>
      <td><?php echo $salesman['first_name'] ?></td>
      <td><?php echo $salesman['last_name'] ?></td>
      <td><?php echo $salesman['email'] ?></td>
      <td><?php echo $salesman['gender'] ?></td>
      <td><?php echo $salesman['mobile'] ?></td>
      <td><?php echo $salesman['status'] ?></td>
      <td><?php echo $salesman['company'] ?></td>
      <td><a href="<?php echo $this->getModelUrl()->getUrl('edit', 'salesman', ['salesman_id' => $salesman['salesman_id']]); ?>">edit</a></td>
      <td><a href="<?php echo $this->getModelUrl()->getUrl('delete', 'salesman', ['salesman_id' => $salesman['salesman_id']]); ?>">delete<a></td>
      <td><a href="<?php echo $this->getModelUrl()->getUrl('grid','salesman_address', ['salesman_id' => $salesman['salesman_id']]); ?>">view address<a></td>
      <td><a href="<?php echo $this->getModelUrl()->getUrl('grid','salesman_price', ['salesman_id' => $salesman['salesman_id']]); ?>">prices<a></td>
    </tr>
    <?php endforeach; ?>
  </table>
</body>
<?php require_once "View/html/footer.phtml" ?>
</html>